"""
State Definition for the Multi-Agent RAG System.

This module defines the schema for the shared state passed between nodes 
in the LangGraph workflow. It uses TypedDict to maintain type safety and 
Annotated lists for efficient data accumulation.
"""

from typing import List, TypedDict, Annotated, Optional, Dict, Any
from langchain_core.documents import Document
import operator

class AgentState(TypedDict):
    """
    Represents the shared memory (state) of the RAG agentic workflow.
    """
    
    # --- Input & Planning ---
    query: str 
    """The original user question."""
    
    plan: Optional[Dict[str, Any]]
    """The strategy generated by the Planner (filters, intent, etc.)."""
    
    optimized_queries: List[str] 
    """A list of refined search terms generated by the Planner."""
    
    # --- Retrieval & Context ---
    documents: Annotated[List[Document], operator.add]
    """
    A list of retrieved document chunks. 
    operator.add ensures new results are appended to existing ones in multi-pass loops.
    """
    
    retriever_content: str 
    """The flattened string version of all retrieved document content for the LLM."""
    
    retrieval_success: bool
    """Flag indicating if any relevant documents were found."""
    
    sources: List[str] 
    """A unique list of source pages or document names used for the answer."""
    
    # --- Generation & Control ---
    generation: str
    """The final answer produced by the Synthesizer."""
    
    revision_notes: str
    """Feedback from previous nodes or human-in-the-loop if a retry is needed."""
    
    retry_count: int
    """Counter to prevent infinite loops in the graph."""
    
    confidence_score: float
    """The self-assessed accuracy score of the final answer."""

